[build]
    functions = "functions/"

[[redirects]]
    from = "getDetails/*"
    to= ".netlify/functions/getDetails"
    status = 200

[[headers]]
    for = "/*"
        [headers.values]
        Access-Control-Allow-Origin = "*"